# Generated by Django 5.2.2 on 2025-06-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('voicebank_avatar', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('year_released', models.CharField(max_length=100)),
            ],
        ),
    ]
